### ISSUE TITLE
What could be finer?  A few badges!

### ISSUE THREAD

**Issue by BurtHarris** [RallySoftware/async-exec#1]
This is great, just what I was looking for.   Thank you.   

The only improvement(s) I might suggest be some badges in the README so that people can quickly identify this module has having TypeScript compatible typing built-in, and perhaps a build status badge based on Appveyor and/or Travis CI..

**Comment by coldpour** [comment]
Thanks for your suggestions Burt!

We're not running this through CI currently so a badge seems a bit premature. If you'd like to suggest some tests, I'd be happy to review them and get this running in Travis at that time.

I'm not sure what problem you're solving by requesting a Typescript badge. Github already categorizes this repo as 100% Typescript. If you npm install this lib into your project, the `prepublish` step will build the typings file for your project to import.

**Comment by BurtHarris** [comment]
I'm looking at packages on npmjs.org.   I don't think github's categorization shows up there, but I could be missing something.   The availability of typing information is a significant factor for me.
